name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test-runner:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Qt
        run: |
          choco install qt5-default -y
          
      - name: Verify directory structure 
        run: Get-ChildItem -Recurse tictactoegui

      - name: Build project
        run: |
          cd tictactoegui
          qmake ttt.pro
          nmake
