name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test-runner:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_mingw81' # Verify the correct arch

      - name: Install MinGW
        run: choco install mingw -y

      - name: Add Qt and MinGW to PATH
        shell: powershell
        run: |
          $qtPath = 'C:\Qt\5.15.2\mingw81_64\bin'
          $mingwPath = 'C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin'
          [System.Environment]::SetEnvironmentVariable('PATH', "$qtPath;$mingwPath;$env:PATH", [System.EnvironmentVariableTarget]::Process)
          Write-Host "Qt and MinGW paths added to PATH: $qtPath, $mingwPath"
          
      - name: Verify Qt and MinGW installation
        shell: powershell
        run: |
          if (-Not (Get-Command qmake -ErrorAction SilentlyContinue)) {
            throw "qmake not found in PATH"
          }
          if (-Not (Get-Command mingw32-make -ErrorAction SilentlyContinue)) {
            throw "mingw32-make not found in PATH"
          }

      - name: Verify directory structure 
        shell: powershell
        run: Get-ChildItem -Recurse tictactoegui

      - name: Build project
        shell: powershell
        run: |
          cd tictactoegui
          qmake ttt.pro
          mingw32-make

      - name: Build unit tests
        shell: powershell
        run: |
          cd UNITTESTZZZZ
          qmake tests.pro
          mingw32-make

      - name: Run unit tests
        shell: powershell
        run: |
          cd UNITTESTZZZZ/build/Desktop_Qt_5_15_2_MinGW_64_bit-Debug/debug
          ./UNITTESTZZZZ.exe
          
      - name: Run executable
        shell: powershell
        run: |
          cd tictactoegui/build/Desktop_Qt_6_7_0_MinGW_64_bit-Debug/debug
          ./ttt.exe
