name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test-runner:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Qt
        run: |
          choco install qt5-sdk --confirm
          RefreshEnv
      
      - name: Add Qt to PATH
        run: |
          $qtPath = 'C:\Qt\5.15.2\msvc2019_64\bin'
          [System.Environment]::SetEnvironmentVariable('PATH', "$qtPath;$env:PATH", [System.EnvironmentVariableTarget]::Process)
          Write-Host "Qt path added to PATH: $qtPath"
          
      - name: Verify directory structure 
        run: Get-ChildItem -Recurse tictactoegui

      - name: Build project
        run: |
          cd tictactoegui
          qmake ttt.pro
          nmake
