name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test-runner:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v3

      - name: Setup MSVC environment
        shell: cmd
        run: |
          "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvars64.bat"

      - name: Verify directory structure 
        shell: powershell
        run: Get-ChildItem -Recurse tictactoegui

      - name: Build project
        shell: cmd
        run: |
          cd tictactoegui
          qmake ttt.pro
          nmake
