name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test-runner:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

      - name: Install Qt using Chocolatey
        run: |
          choco install qt5-default --confirm

      - name: Find Qt installation path
        id: find-qt-path
        shell: powershell
        run: |
         $qtPath = Get-ChildItem -Path "C:\Program Files" -Filter "qmake.exe" -Recurse -File | Select-Object -First 1 -ExpandProperty FullName
         if ($qtPath -eq $null) {
         $qtPath = Get-ChildItem -Path "C:\Program Files (x86)" -Filter "qmake.exe" -Recurse -File | Select-Object -First 1 -ExpandProperty FullName
         }
         echo "##[set-output name=qt-path;]$qtPath"

      - name: Add Qt to PATH
        shell: powershell
        run: |
          $env:Path += ";$qtPath"
          Write-Host "Qt path added to PATH: $qtPath"

      - name: Verify Qt installation
        shell: powershell
        run: |
          if (-Not (Get-Command qmake -ErrorAction SilentlyContinue)) {
            throw "qmake not found in PATH"
          }

      - name: Verify directory structure 
        shell: powershell
        run: Get-ChildItem -Recurse tictactoegui

      - name: Build project
        shell: powershell
        run: |
          cd tictactoegui
          qmake ttt.pro
          nmake
