name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test-runner:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

      - name: Install Qt using Chocolatey
        run: |
          choco install qt5-default --confirm

      - name: Find package path
        id: find-path
        shell: powershell
        run: |
          $path = Get-ChildItem -Path $env:USERPROFILE\AppData\Roaming\npm\node_modules\your-package -Recurse | Select-Object -First 1 -ExpandProperty FullName
          echo "##[set-output name=path;]$path"

      - name: Add Qt to PATH
        shell: powershell
        run: |
          $qtPath = ${{ steps.find-path.outputs.path }}
          $env:Path += ";$qtPath"
          Write-Host "Qt path added to PATH: $qtPath"

      - name: Verify Qt installation
        shell: powershell
        run: |
          if (-Not (Get-Command qmake -ErrorAction SilentlyContinue)) {
            throw "qmake not found in PATH"
          }

      - name: Verify directory structure 
        shell: powershell
        run: Get-ChildItem -Recurse tictactoegui

      - name: Build project
        shell: powershell
        run: |
          cd tictactoegui
          qmake ttt.pro
          nmake
